@startuml
hide empty methods
hide empty fields
hide circle

namespace smv {
  class SmvDataSet <<Abstract>> {
    isEphemeral: Boolean
    dqm(): SmvDQM
    -terminateAtError(checkResult: CheckResult): Unit
    -doRun(): DataFrame
    -computeRDD(): DataFrame
  }

  class CheckResult {
    passed: Boolean
    errorMessages: Seq[String, String]
    checkLog: Seq[String]
    \++(that: CheckResult): CheckResult
  }

  class SmvFile <<Abstract>> extends SmvDataSet {
    failAtParsingError: Boolean
    -parserLogger: RejectLogger
    -checkParserLogger(): CheckResult
    -computeRDD()
  }

  class RejectLogger {
  }

  class SmvCounter {
  }

  SmvDataSet *-- "1" smv.dqm.SmvDQM
  SmvDataSet *-- "*" CheckResult
  SmvFile *-- "1" RejectLogger
}

namespace smv.dqm {

  class DQMPolicy <<Abstract>>{
    name: String
    checkPolicy(df: DataFrame, logger: DQMLogger): Boolean
  }

  class ImplementFailCountPolicy <<Private>> extends DQMPolicy {
    taskName: String
    threshold: Int
    ~cnstr(taskName, threshold)
  }

  class ImplementFailPercentPolicy <<Private>> extends DQMPolicy {
    taskName: String
    threshold: Double
    ~cnstr(taskName, threshold)
  }

  class FailTotalRuleCountPolicy extends DQMPolicy {
    threshold: Int
    cnstr(threshold)
  }

  class FailTotalRulePercentPolicy extends DQMPolicy {
    threshold: Double
    cnstr(threshold)
  }

  class FailTotalFixCountPolicy extends DQMPolicy {
    threshold: Int
    cnstr(threshold)
  }

  class FailTotalFixPercentPolicy extends DQMPolicy {
    threshold: Double
    cnstr(threshold)
  }

  class DQMTask <<Abstract>> {
    name: String
    taskPolicy: DQMTaskPolicy
  }

  class DQMRule extends DQMTask {
    rule: Column
    name: String
    taskPolicy: DQMTaskPolicy
    -logger: RejectLogger
    cnstr(rule, name = null, taskPolicy = FailNone)
    createCheckCol(logger: DQMLogger): (Column, Column)
  }

  class DQMFix extends DQMTask {
    condition: Column
    fix: Column
    name: String
    taskPolicy: DQMTaskPolicy
    -counter: SmvCounter
    cnstr(condition, rule, name = null, taskPolicy = FailNone)
    createFixCol(logger: DQMLogger): Column
  }

  class DQMTaskPolicy <<Abstract>> {
    createPolicy(name: String): DQMSimplyPolicy
  }

  class FailNone extends DQMTaskPolicy
  class FailAny extends DQMTaskPolicy
  class FailCount extends DQMTaskPolicy {
    threshold: Int
  }
  class FailPercent extends DQMTaskPolicy {
    threshold: Double
  }

  class SmvDQM {
    tasks: Seq[DQMTask]
    policies: Seq[DQMPolicy]
    -recordCounter: SmvCounter
    cnstr(tasks, policies)
    add(task: DQMTask): SmvDQM
    add(policy: DQMPolicy): SmvDQM
    -policiesFromTasks(): Seq[DQMPolicy]
    ~isEmpty(): Boolean
    ~attachTasks(df: DataFrame): DataFrame
    ~checkPolicies(df: DataFrame): CheckResult
    applyOnDF(df: DataFrame): CheckResult
  }

  SmvDQM *-- "*" DQMTask
  SmvDQM *-- "*" DQMPolicy
  DQMTask *-- "1" DQMTaskPolicy
}

smv.dqm.DQMRule *-- "1" smv.RejectLogger
smv.dqm.DQMFix *-- "1" smv.SmvCounter
smv.dqm.SmvDQM *-- "1" smv.SmvCounter

@enduml
