@startuml
title run module with DataSetMgr example: x(scala)->y(py)->z(scala)

Actor User
Participant SmvApp as app
Participant DataSetMgr as dsm
Participant SmvModule as mod
Participant DataSetRepoScala as dsrs
Participant DataSetRepoPython as dsrp
Participant IDataSetRepoPy4J as idsrp


User -> app: smv-run -m x
app -> dsm: loadDSWDep('x')
dsm -> dsrs: loadDS('x')
dsrs --> dsm: x: reqUrns=('y')
dsm -> mod: x.resReq( loadDSWDepWState(state) )
mod -> dsm: loadDSWithDepWState(state)('y')
dsm -> dsrs: loadDS('y')
dsrs --> dsm: Unit
dsm -> dsrp: loadDS('y')
dsrp --> dsm: y: reqUrns=('z')
dsm -> mod: y.resReq( loadDSWDepWState(state) )
mod -> dsm: loadDSWDepWState(state)('z')
dsm -> dsrs: loadDS('z')
dsrs --> dsm: z: reqUrns=()
dsm --> mod: z
mod --> dsm: (z)
dsm --> mod: y
mod --> dsm: (y)
dsm --> app: x
app --> app: (run x)
app --> User: (print result)

@enduml
