@startuml

title SMV Python integration class diagram

hide empty methods
hide empty fields
hide circle

package Scala {
  class SmvApp {
    DataSetFactory(fqn: String) : Option[SmvDataSet]
    findExternalModule(fqn: String) : Option[SmvExtModuleInt]
    findExternalInput(fqn: String) : Option[SmvExtInputInt]
  }
  class SmvOutput
  class SmvDataSet
  class SmvInputDataSet extends SmvDataSet
  class Scala.SmvExtModuleInt <<Java>> {
    requiresDS()
    hash()
    run()
    ???()
  }
  class Scala.SmvExtInputInt <<Java>> {
    hash()
    run()
    ???()
  }

  SmvApp o-- Python.SmvPythonRepo
  SmvApp *-- "*" SmvDataSet

  class SmvModuleLink extends SmvModule
  SmvModuleLink *-- SmvOutput

  class SmvModule extends SmvDataSet

  class SmvExtModule extends SmvModule {
    ctor(mod: SmvExtModuleInt)
  }
  SmvExtModule o-- Scala.SmvExtModuleInt

  class SmvExtInput extends SmvInputDataSet {
    ctor(in: SmvExtInputInt)
  }
  SmvExtInput o-- Scala.SmvExtInputInt

  class SmvExtOutputModule extends SmvExtModule
  SmvExtOutputModule -U-|> SmvOutput
}

package Python {
  class SmvPythonRepo {
    findModule(fqn)
    findInput(fqn)
  }
  class SmvPyDataSet

  class SmvPyModule extends Scala.SmvExtModuleInt
  SmvPyModule -U-|> SmvPyDataSet

  class SmvPyInputDataSet extends Scala.SmvExtInputInt
  SmvPyInputDataSet -U-|> SmvPyDataSet

  SmvPythonRepo *-- "*" SmvPyDataSet : "cache"

  SmvPyCsvFile -U-|> SmvPyInputDataSet
}

@enduml
