@startuml
title simple python module resolution and run

Actor User
Participant SmvApp as app
Participant SmvExtModule as extmod
Participant SmvPythonRepo as repo
Participant SmvPyModule as pymod

User -> app : DataSetFactory(fqn)
activate app
  app -> app : findLocalDS(fqn)
  app -> app : findExternalInput(fqn)
  app -> app : findExternalModule(fqn)
  activate app
  app -> repo : findModule(fqn)
    activate repo
      repo -> pymod : <<create>>
      activate pymod
      repo --> app : mod :\nSmvExtModuleInt
    deactivate repo
  deactivate app
  app -> extmod : <<create>>
  activate extmod
  app --> User : DataSet :\nSmvExtModule
deactivate app

User -> extmod : run
extmod -> pymod : run
pymod --> extmod : res
extmod --> User : res

@enduml
