@startuml
hide empty methods
hide empty fields
hide circle

namespace smv {
  class SmvAncillary <<Abstract>> {
    requiresDS(): Seq[SmvModuleLink]
    ~getDF(ds: SmvModuleLink): DataFrame
  }

  class SmvHierarchy {
    name: String
    hierarchyMap: SmvOutput
    hierarchy: Seq[String]
  }

  class SmvHierarchies extends SmvAncillary {
    prefix: String
    hierarchies: Seq[SmvHierarchy]
    - requiresDS(): Seq[SmvModuleLink]
    - applyToDf(df: DataFrame): DataFrame

    hierGroupBy(keys: String*): SmvHierarchies
    withNameCol(): SmvHierarchies
    withParentCols(hierName: String): SmvHierarchies

    levelRollup(df: DataFrame, levels: String*)(aggregations: Column*): DataFrame
    levelSum(df: DataFrame, levels: String*)(valueCols: String*): DataFrame
  }

  class SmvModule {
    requiresAnc() : Seq[SmvAncillary] = Seq.empty
    getAncillary(SmvAncillary) : SmvAncillary
  }

  SmvHierarchies *-- "n" SmvHierarchy
}

namespace myapp {
  class ZipHier extends smv.SmvHierarchies
  class MyModule extends smv.SmvModule

  MyModule -L-> "requires" ZipHier
}

@enduml
