#!/usr/bin/env bash

set -e

SMV_TOOLS="$(cd "`dirname "$0"`"; pwd)"

export PYSPARK_DRIVER_PYTHON="$(which jupyter)"

if [ -f "${HOME}/.jupyter/jupyter_notebook_config.py" ]; then
  export PYSPARK_DRIVER_PYTHON_OPTS="notebook"
else
  export PYSPARK_DRIVER_PYTHON_OPTS="notebook --FileContentsManager.root_dir=notebooks --NotebookApp.open_browser=False"
fi

# Pass through the options from `smv-jupyter` invocation through to `smv-pyshell`
# This will allow the user to specify pyspark options like:
# `smv-jupyter -- --master=yarn-client --num-executors=10`
# `smv-jupyter -- --conf="spark.driver.maxResultSize=0"`
$SMV_TOOLS/smv-pyshell "${@}"
