#!/bin/bash

TEMPLATE_DIR="$(cd "`dirname "$0"`"; pwd)/templates"
TEMPLATE_DATA_DIR="$TEMPLATE_DIR/data"

# PROJ_TYPE:
#  - simple (default)
#  - enterprise
#  - test
PROJ_TYPE="simple"
OVERRIDE=0


while [[ $# -gt 1 ]]
do
FLAG=$1

  case $FLAG in
    -q)
        QUITE_MODE=1
        shift
        ;;
    -b|-blank)
        PROJ_TYPE="blank"
        shift
        ;;
    -s|-simple)
        PROJ_TYPE="simple"
        shift
        ;;
    -e|-enterprise)
        PROJ_TYPE="enterprise"
        shift
        ;;
    -t|-test)
        PROJ_TYPE="test"
        shift
        ;;
    -b|-big)
        PROJ_TYPE="big"
        shift
        ;;
    -dd|-dataDir)
        PROJ_DATA_DIR="$2"
        shift
        shift
        ;;
    -n|-name)
        PROJ_NAME="$2"
        shift
        shift
        ;;
    -o)
    OVERRIDE=1
        shift
        ;;
    -gi|-gitinit)
        DO_GIT_INIT=1
        shift
        ;;
    *)
        ;;
  esac
done

TEMPLATE_DIR+="/$PROJ_TYPE"

if [ $# -ne 1 ]; then
    echo "ERROR: Invalid number of arguments"
    echo "USAGE: $0 [-q][-o] [-s|-e|-t|-b] [-dd] [-n]  project_path"
    echo "project types:"
    echo "  -s: simple (default)"
    echo "  -e: enterprise"
    echo "  -t: test (for developers only)"
    echo "  -b: blank/empty project"
    echo "  -dd: data directory"
    echo "  -n: project name"
    echo "  -gi: initializes git repo in project directory"
    echo
    echo "example:"
    echo "    simple:     \$ ./tools/smv-init /project/path"
    echo "    blank:      \$ ./tools/smv-init -b -n projec_name -dd /data/dir /project/path"
    echo "    enterprise: \$ ./tools/smv-init -e /project/path"
    exit 1
fi

PROJ_DIR="$1"
PROJ_CLASS=""
STAGE_NAME="`echo $PROJ_NAME | tr '[:upper:]' '[:lower:]'`"
PROJ_DATA_DIR=${PROJ_DATA_DIR:="${PROJ_DIR}/data"} # default data dir is /data in project dir

# proj class hardcoded for smv integration tests
if [ "$PROJ_TYPE" = "test" ]; then
  PROJ_CLASS="integration.test"
fi

function extract_group_artifact_ids()
{
    PROJ_GROUP_ID="${PROJ_CLASS%.*}"
    PROJ_ARTIFACT_ID="${PROJ_CLASS##*.}"

    if [ "$PROJ_GROUP_ID" == "$PROJ_ARTIFACT_ID" ]; then
        echo "Invalid project class: $PROJ_CLASS"
        echo "the class must have at least two levels a.b"
        exit 1
    fi
}

function create_proj_dir()
{
    echo "-- creating project directory"

    if [ -d "$PROJ_DIR" ]; then
      if [ $OVERRIDE -eq 0 ]; then
        echo "   $PROJ_DIR already exists, use the -o flag to authorize override."
        exit 1
      else
        echo "   $PROJ_DIR already exists, converting to SMV project..."
      fi

      # if creating SMV project from existing dir, it must not contain an smv-app-conf.props file
      if [ -f "$PROJ_DIR/conf/smv-app-conf.props" ]; then
        echo "   Error: $PROJ_DIR is already an SMV project. Quitting."
        exit 1
      fi
    fi

    mkdir -p "$PROJ_DIR"
    export PROJ_DIR_FULL_PATH=$(cd $PROJ_DIR; /bin/pwd)
}

function copy_with_inject()
{
    ESCAPED_FULL_PATH=$(echo ${PROJ_DIR_FULL_PATH} | sed -e 's/[\/&]/\\&/g')
    ESCAPED_DATA_DIR=$(echo ${PROJ_DATA_DIR} | sed -e 's/[\/&]/\\&/g')

    SRC="$1"
    DST="$2"

    mkdir -p "$(dirname "$DST")"
    sed -e "s/_GROUP_ID_/$PROJ_GROUP_ID/" \
        -e "s/_ARTIFACT_ID_/$PROJ_ARTIFACT_ID/" \
        -e "s/_PROJ_CLASS_/$PROJ_CLASS/g" \
        -e "s/_PROJ_DIR_FULL_PATH_/${ESCAPED_FULL_PATH}/g" \
        -e "s/_PROJ_NAME_/$PROJ_NAME/g" \
        -e "s/_STAGE_NAME_/$STAGE_NAME/g" \
        -e "s/_PROJ_DATA_DIR_/$ESCAPED_DATA_DIR/g" \
        < "$SRC" > "$DST"
}

function copy_conf_files()
{
    # copy appropriate files based on project type
    PYTHON_FILES="README.md notebooks/Untitled.ipynb .gitignore.template log4j.properties conf/smv-app-conf.props conf/smv-user-conf.props"
    SCALA_FILES="$PYTHON_FILES build.sbt pom.xml project/assembly.sbt project/build.properties"
    ENTERPRISE_FILES="$PYTHON_FILES conf/smv-user-conf.props.template"

    if [ "$PROJ_TYPE" = "test" ] ; then
      for f in $SCALA_FILES; do
          copy_with_inject "$TEMPLATE_DIR/$f" "$PROJ_DIR/$f"
      done
    elif [ "$PROJ_TYPE" = "enterprise" ] ; then
      for f in $ENTERPRISE_FILES; do
          copy_with_inject "$TEMPLATE_DIR/$f" "$PROJ_DIR/$f"
      done
    else
      for f in $PYTHON_FILES; do
          copy_with_inject "$TEMPLATE_DIR/$f" "$PROJ_DIR/$f"
      done
    fi

    # .gitignore was postfixed with .template so it does not affect SMV's git repo
    mv "$PROJ_DIR/.gitignore.template" "$PROJ_DIR/.gitignore"
}

function copy_data_files()
{
    if [ "$PROJ_TYPE" != "blank" ]; then
        data_dir=$1

        echo "-- copying data files"

        cp -R "$data_dir" "$PROJ_DIR"
    fi
}

function copy_src_dir()
{
    subdir=$1
    proj_cp=$2
    DST_DIR="${PROJ_DIR_FULL_PATH}/src/${subdir}/${proj_cp}"

    (cd ${TEMPLATE_DIR}/src/${subdir}; find . -type f | while read f; do
      SRC_FILE="${TEMPLATE_DIR}/src/${subdir}/$f"
      DST_FILE="${DST_DIR}/$f"
      copy_with_inject "$SRC_FILE" "$DST_FILE"
    done)
}

function copy_src_files()
{
    echo "-- copying source files"

    PROJ_CLASS_PATH="`echo $PROJ_CLASS | sed -e 's/\./\//g'`"

    if [ "$PROJ_TYPE" = "test" ]; then
      for subdir in main/scala main/python; do
          copy_src_dir ${subdir} ${PROJ_CLASS_PATH}
      done
    else
      STAGE_NAME_PATH="`echo $STAGE_NAME | sed -e 's/\./\//g'`"

      for subdir in main/python; do
          copy_src_dir ${subdir} ${STAGE_NAME_PATH}
      done
    fi
}

function create_python_packages()
{
    echo '-- creating python packages'
    for dir in $(ls -d ${PROJ_DIR_FULL_PATH}/src/main/python/*/); do
        find ${dir} -type d -print0 | xargs -0 -I\{\} touch \{\}/__init__.py
    done
}

function create_notebooks_folder()
{
  echo "--  creating notebooks folder"

  cd ${PROJ_DIR_FULL_PATH} && mkdir notebooks && touch notebooks/_jupyter_notebooks_
}

function create_library_folder()
{
    echo "-- creating library folder"

    cd ${PROJ_DIR_FULL_PATH} && mkdir library
}

function create_git_structure()
{
    if [ "$DO_GIT_INIT" = 1 ]; then
        echo "-- initializing git repository"

        cd ${PROJ_DIR_FULL_PATH} && git init && git add . && git commit -m "init commit"
    fi
}

# --- MAIN ---

#  only test proj has PROJ_CLASS
if [ "$PROJ_TYPE" = "test" ] ; then
  extract_group_artifact_ids
fi

create_proj_dir
copy_conf_files

if [ "$PROJ_TYPE" = "test" ]; then
  copy_data_files "$TEMPLATE_DIR/data"
else
  copy_data_files $TEMPLATE_DATA_DIR
fi

copy_src_files
create_python_packages

if [ "$PROJ_TYPE" = "big" ] ; then
  $TEMPLATE_DIR/dupMod.sh $PROJ_DIR/src/main/python/stage1/employment.py $PROJ_DIR/src/main/python/stage1/ 1000
  rm $PROJ_DIR/src/main/python/stage1/employment.py
fi

create_notebooks_folder
create_library_folder
create_git_structure
