#! /usr/bin/env bash

set -e

echo "========================================"
echo "WARNING: smv-pyshell is deprecated. Please use smv-shell instead!"
echo "========================================"

smv-shell "$@"