#!/usr/bin/env bash

# Start a SMV runtime server.
# USAGE: smv-server [-e server_script] smv_app_args -- spark_args
SMV_TOOLS="$(cd "`dirname "$0"`"; pwd)"

# need to extract the -e option before source _env.sh!
ENTRY_SCRIPT="${SMV_TOOLS}/../src/main/python/scripts/smvserver.py"
if [ $1 = "-e" ]; then
  ENTRY_SCRIPT="$2"
  shift; shift
fi

source ${SMV_TOOLS}/_env.sh
source ${SMV_TOOLS}/_pyenv.sh

echo "START SMV SERVER =============================="

run_pyspark_with "${ENTRY_SCRIPT}"
