#!/bin/bash

SMV_TOOLS="$(cd "`dirname "$0"`"; pwd)"
source $SMV_TOOLS/_env.sh

export SMV_APP_HOME="$(pwd)"
export SMV_HOME="$(cd "${SMV_TOOLS}/.."; pwd)"
export SMV_APP_JAR="$SMV_APP_HOME/$APP_JAR"
export R_PROFILE="${SMV_TOOLS}/conf/sparkR_init.r"

set_spark_home

if type rstudio &> /dev/null; then
  R_CMD="rstudio"
else
  R_CMD="open -a Rstudio ."
fi

if [[ "$1" = "-g" || "$1" = "-rs" ]]; then
  eval $R_CMD
else
  R
fi
