#!/usr/bin/env bash

# Start a SMV runtime server.
# USAGE: smv-server smv_app_args -- spark_args

SMV_TOOLS="$(cd "`dirname "$0"`"; pwd)"
source ${SMV_TOOLS}/_env.sh
source ${SMV_TOOLS}/_pyenv.sh

echo "START SMV SERVER =============================="

run_pyspark_with ${SMV_TOOLS}/../src/main/python/scripts/smvserver.py
