#!/usr/bin/env bash

# Start a SMV runtime server.
# USAGE: smv-server [-h] spark_args smv_app_args

SMV_TOOLS="$(cd "`dirname "$0"`"; pwd)"
source ${SMV_TOOLS}/_env.sh
source ${SMV_TOOLS}/_pyenv.sh

echo "START SMV SERVER =============================="

#spark-submit \
#  --executor-memory ${EXECUTOR_MEMORY} \
#  --driver-memory ${DRIVER_MEMORY} \
#  --master ${MASTER} \
#  --jars ${APP_JAR} \
#  --driver-class-path "$APP_JAR"
#  $1 ${ARGS[@]}

run_pyspark_with ${SMV_TOOLS}/../server/start.py
