#!/bin/bash

SMV_TOOLS="$(cd "`dirname "$0"`"; pwd)"
source $SMV_TOOLS/_env.sh

export SMV_HOME="$(cd "${SMV_TOOLS}/.."; pwd)"
export R_PROFILE="${SMV_TOOLS}/conf/sparkR_init.r"
export SMV_APP_JAR="$APP_JAR"

set_spark_home

R

