#!/usr/bin/env bash
#
# Start the smv class server.
# USAGE: smv-class-server [port]
#
# The optional port number can be specified to override port number specified in config.

set -e
if [ "$1" = "-h" ]; then
  echo "USAGE: `basename $0` [-h] [port]"
  echo "  port : optional port number to listen for requests"
  exit 0
fi

SMV_TOOLS="$(cd "`dirname "$0"`"; pwd)"
source $SMV_TOOLS/_env.sh

echo "STARTING SERVER =============================="

# TODO: should replace scala with java and add spark jar to class path to pick up Scala.* and all other common libraries.

# TODO: should honor port value passed on command line.
scala -cp "$APP_JAR" org.tresamigos.smv.class_loader.ClassLoaderServer




