#!/usr/bin/env bash
#
# Run SMV unit tests
# USAGE: smv-pytest [-h] -- spark_args
#
# TODO: add test arguments, e.g. to specify a single test to run
#
# user can specify spark args (such as --master, --class or --jar to override the fat jar selection)
# the rest of the arguments are the standard SmvApp arguments.

set -e
SMV_TOOLS="$(cd "`dirname "$0"`"; pwd)"
source $SMV_TOOLS/_env.sh
source $SMV_TOOLS/_pyenv.sh

if [ "$1" = "-h" ]; then
  show_run_usage_message `basename $0`
  exit 0
fi

run_pyspark_with ${SMV_TOOLS}/../python/runtests.py
