#!/usr/bin/env bash
#
# Run one or more SMV modules / stages / app.
# USAGE: smv-run [-h] [--script <script-path> [--script-opt <option>]*] <smv_app_args> [-- spark_args]
#
# user can specify optional spark args (such as --master, --executor-memory, etc)

set -e
SMV_TOOLS="$(cd "`dirname "$0"`"; pwd)"
source $SMV_TOOLS/_env.sh
source $SMV_TOOLS/_pyenv.sh

if [ "$1" = "-h" ]; then
  show_run_usage_message `basename $0`
  exit 0
fi

echo "START RUN =============================="
date

SMV_SCRIPT="${SMV_USER_SCRIPT:-${SMV_TOOLS}/../src/main/python/scripts/runapp.py}"
if [ -n "${SMV_USER_SCRIPT}" ]; then
  SMV_SCRIPT_OPTS="${SMV_USER_SCRIPT_OPTS[@]}"
fi

run_pyspark_with "$SMV_SCRIPT $SMV_SCRIPT_OPTS"

date
