#!/bin/bash
set -e

target_dir="$1"

if [ -z "$target_dir" ]; then
  echo "No target directory specified."
  exit 1
fi

smv_tools="$(cd "`dirname "$0"`"; pwd)"
spark_version=$(cat "$smv_tools"/../.spark_version)

remote_tarball="http://www-us.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz"
local_tarball=$(basename $remote_tarball)
echo "[INFO] Downloading $remote_tarball to $local_tarball."
curl -OL --progress-bar --fail "$remote_tarball" > "$local_tarball"

tar -zxf "$local_tarball"
rm -rf "$local_tarball"
spark_dir="${local_tarball%.tgz}"
mv "$spark_dir" "$target_dir"

echo "[INFO] Spark installed succesfully!"
