@startuml

hide empty methods
hide empty fields
hide circle

package Scala {
  class SmvApp
  class DataSetMgr {
    loadDataSetWithDep(fqn: String): SmvDataSet
    loadDataSetWithDep(fqns: List[String]): List(SmvDataSet)
  }
  class DataSetRepo {
    loadDataSet(fqn: String): SmvDataSet
  }
  class DataSetRepoScala extends DataSetRepo
  class DataSetRepoPython extends DataSetRepo
  class IDataSetRepoPy4J <<java>>
  class SmvModule
  class SmvExtModule extends SmvModule
  class SmvExtModulePython extends SmvModule
  class ISmvModulePy4J <<java>>

  SmvApp *-- DataSetMgr
  DataSetMgr .. DataSetLoadState
  DataSetMgr *-- "*" DataSetRepo
  DataSetRepo ..> SmvModule : "create"
  SmvExtModulePython *-- ISmvModulePy4J
  DataSetRepoPython *-- IDataSetRepoPy4J
  IDataSetRepoPy4J ..> ISmvModulePy4J : "create"
}

package Python {
  class PythonDataSetRepo extends IDataSetRepoPy4J
  class SmvPyModule extends ISmvModulePy4J
}

@enduml
